use_frameworks!

platform :ios, '9.0'

target 'HPParallaxHeader_Example' do
  pod 'HPParallaxHeader', :path => '../'
  pod 'Parchment'
  target 'HPParallaxHeader_Tests' do
    inherit! :search_paths

    
  end
end
